# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# curl -H "xos-username: admin@opencord.org" -H "xos-password: letmein" -X POST --data-binary @mcord-barcelona-routes.yaml http://192.168.69.1:30007/run

tosca_definitions_version: tosca_simple_yaml_1_0
imports:
  - custom_types/site.yaml
  - custom_types/deployment.yaml
  - custom_types/sitedeployment.yaml
  - custom_types/node.yaml
  - custom_types/vrouterservice.yaml
  - custom_types/vrouterserviceinstance.yaml

description: Configures the MCORD POD Fabric Static Routes

topology_template:
  node_templates:

    # Site deployment
    mySite:
      type: tosca.nodes.Site
      properties:
          name: mysite
          login_base: opencord
          abbreviated_name: ms
          site_url: http://opencord.org/
          hosts_nodes: true

    myDeployment:
      type: tosca.nodes.Deployment
      properties:
        name: mydeployment

    site_deployment:
      type: tosca.nodes.SiteDeployment
      requirements:
        - site:
            node: mySite
            relationship: tosca.relationships.BelongsToOne
        - deployment:
            node: myDeployment
            relationship: tosca.relationships.BelongsToOne

    # compute nodes
    node#node1:
        type: tosca.nodes.Node
        properties:
            dataPlaneIntf: eth2
            dataPlaneIp: 118.0.0.201
            name: node1
        requirements:
            - site_deployment:
                node: site_deployment
                relationship: tosca.relationships.BelongsToOne

    node#node2:
        type: tosca.nodes.Node
        properties:
            dataPlaneIntf: eth2
            dataPlaneIp: 118.0.0.202
            name: node2
        requirements:
            - site_deployment:
                node: site_deployment
                relationship: tosca.relationships.BelongsToOne

    node#node3:
        type: tosca.nodes.Node
        properties:
            dataPlaneIntf: eth2
            dataPlaneIp: 118.0.0.203
            name: node3
        requirements:
            - site_deployment:
                node: site_deployment
                relationship: tosca.relationships.BelongsToOne

    # static routes

    service#vrouter:
        type: tosca.nodes.VRouterService
        properties:
            name: vrouter
            must-exist: true
        requirements:
            - owner:
                node: service#vrouter
                relationship: tosca.relationships.BelongsToOne


    vroutersi#calico:
        type: tosca.nodes.VRouterServiceInstance
        properties:
          name: calico